### model
model_name_or_path: /lustre/huangyk/model_down/DeepSeek-R1-Distill-Qwen-32B
trust_remote_code: true
  #quantization_bit: 4

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
#lora_target: ["q_proj","v_proj"]
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
use_unsloth: false
use_galore: false
flash_attn: auto
deepspeed: examples/deepspeed/ds_z3_DS.json

### dataset
dataset: dpo_zh_stage2
template: qwen
cutoff_len: 10000
max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/DS_0423/lora/dpo
logging_steps: 1
save_total_limit: 8
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 8.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
optim: paged_adamw_32bit
gradient_checkpointing: true

### eval
# eval_dataset: dpo_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
